### ISSUE TITLE
Problem in the Training Algorithm Levenberg Marquardt

### ISSUE THREAD

**Issue by homarques** [encog/encog-java-core#107]
The algorithm stop sometimes when it is in iteration 323 and error 69.01548627767082, It always stop theses values.

**Comment by jeffheaton** [comment]
There have been a few fixes to the LMA training since this was posted.  If anyone is still having an issue with this type of training please provide code to reproduce and I will investigate.

**Comment by jauten** [comment]
Thanks Jeff, I will try to test it out at some point and let you know.
