### ISSUE TITLE
Evaluate adding LSTM network to Encog

### ISSUE THREAD

**Issue by jeffheaton** [encog/encog-java-core#165]
There have been several requests to add a LSTM network to Encog. Some discussion of it here.  http://www.heatonresearch.com/comment/1231#comment-1231

Wikipedia Entry: http://en.wikipedia.org/wiki/Long_short_term_memory
More formal description:  ftp://ftp.idsia.ch/pub/juergen/lstm.pdf

At this point I am unfamiliar with this architecture, so I am adding this issue to track it.  Any suggestions/comments are welcome.

Initial thoughts... could this be implemented with the freeform networks.  Or would it be better to create a new MLMethod.

**Comment by szymanowski** [comment]
+ 1 to this too.
Interesting lecture series on deep learning.
Deep Learning Lecture 12: Recurrent Neural Nets and LSTMs
https://www.youtube.com/watch?v=56TYLaQN4N8

**Comment by Sebubu** [comment]
+1 too

**Comment by cognivator** [comment]
another +1

**Comment by Joshuaalbert** [comment]
I'm working on this also. Any collaborators willing to bandy ideas about?

**Comment by Turakar** [comment]
@Joshuaalbert 

What's the status of your work? Can you publish it in a repository?

**Comment by Joshuaalbert** [comment]
It is nearly working. Working on a temporal connectionist training for it, to allow unaligned pattern training.

**Comment by automenta** [comment]
our latest version is here, it's pure java (not involving any encog). it has an experimental continuous / online learning mode

https://github.com/automenta/narchy/tree/skynet1/logic/src/main/java/nars/learn/lstm

 it would be nice to add the new Grid LSTM also

**Comment by zjuhasz** [comment]
Any updates on this? I'd really like to see it added.

**Comment by automenta** [comment]
i dont have any updates with any LSTM code. but here's a new variation that might be good too:
https://arxiv.org/abs/1709.02755

**Comment by jeffheaton** [comment]
I am going to close at this point, as I am not actively looking at adding every possible algorithm to Encog.  At this point I am mainly adding ones that I have need of and are not well represented elsewhere.  Also, it sounds like LSTM's future may be uncertain, based on several sources, but summarized nicely here:  https://towardsdatascience.com/the-fall-of-rnn-lstm-2d1594c74ce0
