### ISSUE TITLE
ReLU activation

### ISSUE THREAD

**Issue by nitbix** [encog/encog-java-core#185]
Hi, is anybody already working on adding Rectified Linear Units (ReLU)? Otherwise I'll work on adding support for them - seems easy enough.

**Comment by nitbix** [comment]
Hi guys,

sorry for resurrecting an old conversation, but did we reach an agreement
here in the end or should I just go ahead and do my own thing separately
for the time being?

Thanks,

Alan

On 21 November 2014 at 15:18, ekerazha <notifications@github.com> wrote:

> Mocha ( https://github.com/pluskid/Mocha.jl) docs say:
>
> ReLU is actually not differentialble at 0. But it has subdifferential
> [0,1]. Any value in that interval could be taken as a subderivative, and
> could be used in SGD if we generalize from gradient descent to subgradient
> descent. In the implementation, we choose 0.
>
> Source: http://mochajl.readthedocs.org/en/latest/user-guide/neuron.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/encog/encog-java-core/issues/185#issuecomment-63983889>
> .
>



-- 
  Alan

**Comment by nitbix** [comment]
Given the lack of response, I'm just going to go ahead and write my own. I
can contribute it back if there is interest.

On 1 March 2015 at 19:36, nitbix <nitbix@nitbix.com> wrote:

> Hi guys,
>
> sorry for resurrecting an old conversation, but did we reach an agreement
> here in the end or should I just go ahead and do my own thing separately
> for the time being?
>
> Thanks,
>
> Alan
>
> On 21 November 2014 at 15:18, ekerazha <notifications@github.com> wrote:
>
>> Mocha ( https://github.com/pluskid/Mocha.jl) docs say:
>>
>> ReLU is actually not differentialble at 0. But it has subdifferential
>> [0,1]. Any value in that interval could be taken as a subderivative, and
>> could be used in SGD if we generalize from gradient descent to subgradient
>> descent. In the implementation, we choose 0.
>>
>> Source: http://mochajl.readthedocs.org/en/latest/user-guide/neuron.html
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/encog/encog-java-core/issues/185#issuecomment-63983889>
>> .
>>
>
>
>
> --
>   Alan
>



-- 
  Alan

**Comment by ekerazha** [comment]
Adding the ReL activation function is trivial, but there's the question about differentiability at 0.

**Comment by ekerazha** [comment]
This was my implementation:

		public final void activationFunction(final double[] x, final int start,
				final int size) {
	
			for (int i = start; i < start + size; i++) {
				if (x[i] < 0) {
					x[i] = 0;
				}
			}
		}

and

		public final double derivativeFunction(double b, double a) {
			if (b > 0) {
				return 1;
			} else {
				return 0;
			}
		}

**Comment by nitbix** [comment]
Yes, hence the question on whether there was a consensus on what to do. I'm
going to use 0 in my own fork and not contribute it back - that's what I
meant by "write my own".

On 5 March 2015 at 09:20, ekerazha <notifications@github.com> wrote:

> Adding the ReL activation function is trivial, but there's the question
> about differentiability at 0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/encog/encog-java-core/issues/185#issuecomment-77331150>
> .
>



-- 
  Alan

**Comment by nitbix** [comment]
Thanks, that's almost exactly what I ended up doing as well.

On 5 March 2015 at 09:41, ekerazha <notifications@github.com> wrote:

> This was my implementation:
>
>     public final void activationFunction(final double[] x, final int start,
>             final int size) {
>
>         for (int i = start; i < start + size; i++) {
>             if (x[i] < 0) {
>                 x[i] = 0;
>             }
>         }
>     }
>
> and
>
>     public final double derivativeFunction(double b, double a) {
>         if (b > 0) {
>             return 1;
>         } else {
>             return 0;
>         }
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/encog/encog-java-core/issues/185#issuecomment-77334215>
> .
>



-- 
  Alan

**Comment by t3476** [comment]
A smooth approximation to the reLU is softplus. By softplus:
f(x) = ln(1 + e^x) 
f'(x) = 1/(1+e^(-x))
f'(0) = 0.5
It looks a reasonable choice for derivative of reLU at zero because it's the middle of left and right derivative at zero.
Or just use softplus rather than reLU.

**Comment by jeffheaton** [comment]
For Encog 3.4 I've been using this with:

`	public final double derivativeFunction(final double b, final double a) {
		if(b <= this.params[ActivationReLU.PARAM_RELU_LOW_THRESHOLD])
		{
			return 0;
		}
		return 1.0;
	}`

It seems to converge well.  I believe it common convention for the derivative to be 0 at zero.  Such as:  [http://kawahara.ca/what-is-the-derivative-of-relu/](http://kawahara.ca/what-is-the-derivative-of-relu/)
