### ISSUE TITLE
BLAS/CUBLAS Library help for you

### ISSUE THREAD

**Issue by jduke32** [encog/encog-java-core#199]
Hello , there is new OpenCL/Cuda supported library.
ArrayFire!
http://www.arrayfire.com

There is java wrapper 
https://github.com/arrayfire/arrayfire_java

This library is very fast and open source!
Its commercial but there is open source solution also.
Its apache license now.

You can use its own BLAS/CUBLAS Libraries.
There is also advanced matrix libraries inside.

You can check their page.

**Comment by jeffheaton** [comment]
Thank you for the suggestion.  At this point I am keeping Encog as pure Java. Adding in Native code or GPU support is just a large time commitment than I have right now-- especially when there are several large efforts providing similar (TensorFlow, MXNet, etc.)
