### ISSUE TITLE
Link to the wiki returns page not found

### ISSUE THREAD

**Issue by lodenrogue** [encog/encog-java-core#221]
Going to this url: http://www.heatonresearch.com/wiki/Getting_Started or any /wiki page returns a page not found response.

**Comment by MrMormon** [comment]
It used to have a wonderful resource on flat spots.

**Comment by jeffheaton** [comment]
Sorry about the pages, basically having the website run by Drupal and MediaWiki was turning into a bit of a maintenance nightmare.  Mostly from spammer scripts. I will be adding more of the content.  If there is a page you particularly need, let me know.  It is not simply a matter of copying everything, as some reformatting is needed.  Also some of the pages were out of date, so I am reworking some content.

I just added the Flat Spot Problem back: http://www.heatonresearch.com/encog/flat_spot.html

The getting started (for Encog) is getting a fairly major overhaul and will be added soon.

For now I am leaving this issue open, if there is something you need added, please reply.
