### ISSUE TITLE
SOM clustering

### ISSUE THREAD

**Issue by edilsonacjr** [encog/encog-java-core#228]
The method of clustering the grid of the SOM network is not specified in the documentation, do you have the original paper of the method or is this a original work?

**Comment by jeffheaton** [comment]
It was from the book: Practical Neural Network Recipies in C++, by Timothy Masters, 0124790402.  I will add to the Javadoc.

**Comment by jeffheaton** [comment]
Added to comment.  APA citation: Masters, T., & Schwartz, M. (1994). Practical neural network recipes in C. IEEE Transactions on Neural Networks, 5(5), 853-853.
