### ISSUE TITLE
Is Java 8 Required for Encog now?

### ISSUE THREAD

**Issue by exfenestram** [encog/encog-java-core#229]
Encog fails to compile with OpenJDK 7 (an example is src/main/java/org/encog/ml/importance/AbstractFeatureImportance.java Line 65) - has the compiler requirement advanced to Java 8?

**Comment by jeffheaton** [comment]
Good catch, sorry about that, I will correct that.  Java 8 should not be required.

**Comment by jeffheaton** [comment]
Removed offending piece of code.
