### ISSUE TITLE
Absence of a contributor guide

### ISSUE THREAD

**Issue by willhs** [encog/encog-java-core#232]
Hi.
I'm working on an honours project involving HyperNEAT and am interested in making some small contributions to this project. I tried to find a contributor guide / instructions for this project and eventually found some instructions in the [developer guide](https://s3.amazonaws.com/heatonresearch-books/free/encog-3_3-devguide.pdf):

> If you would like to contribute code back to the Encog project, it is suggested
> that you fork one of the above projects. You can then issue a pull request for
> your forked copy of Encog once you complete your changes. If your changes
> are accepted, they will be merged into the main Encog project. For more
> information on forking a GitHub project refer to the following URL:
> https://help.github.com/articles/fork-a-repo/

However this was under the heading _Acquiring the Encog Core Files_ in the _Building the Encog Core Files_ chapter which isn't the most obvious place to find such information. Perhaps there could be a dedicated "contributor guidelines" document, even if those guidelines are simple? I'm new to contributing to open source projects, so maybe this feature is needless in this case, however I thought I would ask.

Regards.

**Comment by jeffheaton** [comment]
Yes good point, and I will improve this.  If you have code to contribute to Encog, a pull request works best, along with an example and unit test would be idea.

**Comment by jeffheaton** [comment]
http://www.heatonresearch.com/encog/contributor/
