### ISSUE TITLE
Is there  a Backpropagation example by java

### ISSUE THREAD

**Issue by kscorpio** [encog/encog-java-core#235]
In java examples , MLMethodFactory just has several limited model type , does not have Backpropagation , 

how to use Backpropagation  by java(a demo for Backpropagation/BackpropagationFactory)

**Comment by jeffheaton** [comment]
Good point, I will add such an example soon.

**Comment by jeffheaton** [comment]
Those classes are used mainly internally by Encog Analyst, so I really do not create examples of how to use them.  If you want to see how analyst uses them, this is a good example:

https://github.com/encog/encog-java-core/blob/master/src/main/java/org/encog/app/analyst/commands/CmdTrain.java

Also, training is created by its own set of factories:  https://github.com/encog/encog-java-core/tree/master/src/main/java/org/encog/ml/factory/train
