### ISSUE TITLE
How to build a RBF network with two output neurons

### ISSUE THREAD

**Issue by ChrisCSIE** [encog/encog-java-core#242]
i want to build a RBF network base on **MultiRadial.java**  (https://github.com/encog/encog-java-examples/blob/master/src/main/java/org/encog/examples/neural/radial/MultiRadial.java)

but in **MultiRadial.java**, it use SVDTraining as MLTrain, so it only use one output neuron

What kind of **Training Type** I should use for build a RBFN with two output neurons?

**Comment by jeffheaton** [comment]
It is quite true that SVD requires a single output neuron.  For multiple output neurons you will need to use backpropagation.  It will not be as effective, but it should work.
