### ISSUE TITLE
Activation function from a wrong layer

### ISSUE THREAD

**Issue by ahsimb** [encog/encog-java-core#243]
package org.encog.neural.networks.training.propagation;

public class GradientWorker implements EngineTask {
...
	private void processLevel(final int currentLevel) {
		final int fromLayerIndex = this.layerIndex[currentLevel + 1];
		final int toLayerIndex = this.layerIndex[currentLevel];
		final int fromLayerSize = this.layerCounts[currentLevel + 1];
		final int toLayerSize = this.layerFeedCounts[currentLevel];

		final int index = this.weightIndex[currentLevel];
		final ActivationFunction activation = this.network
				.getActivationFunctions()[currentLevel]; // SHOULD BE currentLevel + 1 SHOULDN'T IT?
		final double currentFlatSpot = this.flatSpot[currentLevel + 1];
   ...
   }
...
}

**Comment by jeffheaton** [comment]
Thanks, very good catch!
