### ISSUE TITLE
OpenCL backend in Java Encog 3

### ISSUE THREAD

**Issue by InonS** [encog/encog-java-core#245]
I posted [a SO question](https://stackoverflow.com/q/44997049) since it seems that community is more active (4k questions vs. 76 GH issues).

Could someone please take a look?
Thanks.

**Comment by rjpg** [comment]
I think it is hard now  to catch up with tensorflow. My advice is to learn tensorflow and see how to load the models in Java.

**Comment by InonS** [comment]
@rjpg thank you for your candor, but I don't think that counts as a valid way to address my issue.

The simple question remains: **Does Encog not support OpenCL** since ver. 3, or does it? And if it does, can I see a *working example* of it?

**Comment by jeffheaton** [comment]
OpenCL is not currently supported by Encog.
