### ISSUE TITLE
mvnrepositor cannot version 3.4 ？

### ISSUE THREAD

**Issue by qzhJie** [encog/encog-java-core#248]
i want to use encog 3.4 by maven, but mvnrepositor without it version 3.4

**Comment by Teka101** [comment]
👍 need too

**Comment by jeffheaton** [comment]
Yes this is long overdue!  This is next on my list!

**Comment by jeffheaton** [comment]
Okay, Encog 3.4 has been released, see: [link](https://github.com/encog/encog-java-core/releases/tag/v3.4)
It has been pushed to Nexus OSS Maven repo, and will propagate to the others.  Refer to the examples build.gradle for more info: [link](https://github.com/encog/encog-java-examples/blob/master/build.gradle)

Note: that it might take a day or to for all repos to pick it up.  For now it is in Nexus (you can pull from there already, refer to the examples Gradle script for info).  

_<dependency>
  <groupId>org.encog</groupId>
  <artifactId>encog-core</artifactId>
  <version>3.4</version>
</dependency>_

**Comment by jeffheaton** [comment]
Encog 3.4 is now in Maven central.  Note that the version number is "3.4" and not 3.4.0".

https://search.maven.org/#artifactdetails%7Corg.encog%7Cencog-core%7C3.4%7Cjar

**Comment by Teka101** [comment]
Thank you ! 💯
